[survey]
title = "NixCon 2026 survey"
intro = "Welcome to the NixCon 2026 survey! Please take a few minutes to fill out this survey with info about your experience at NixCon 2026. Even if you did not attend in person, we'd be happy to hear about why that is. Feel free to skip any questions you have no particular opinion about."

[groups.meta]
title = "Meta"

[groups.livestream]
title = "Live stream"
description = "For those who joined remotely via livestream."

[groups.schedule]
title = "Schedule"
description = "For those who joined remotely or in-person."

[groups.social]
title = "Social"
description = "For those who joined in-person."

[groups.venue]
title = "Venue"
description = "For those who joined in-person."

[groups.other]
title = "Other"

[questions.attended]
prompt = "Did you attend NixCon 2026?"
choices.inPerson = "Yes, in person"
choices.livestream = "Yes, via livestream"

[questions.enjoyment]
prompt = "How did you enjoy NixCon 2026 on a scale from 1 (bad) to 5 (good)?"
help = "If you joined remotely or in-person."
choices.v1 = "1 (bad)"
choices.v2 = "2"
choices.v3 = "3"
choices.v4 = "4"
choices.v5 = "5 (good)"

[questions.whyNotAttend]
prompt = "If you wanted to come to this NixCon but could not make it, why not?"
help = "If you joined remotely or not at all. Select all that apply."
choices.ticketTooExpensive = "Ticket too expensive"
choices.accommodationTooExpensive = "Accommodation too expensive"
choices.travelTooExpensive = "Travel too expensive"
choices.environmentalImpact = "Environmental impact of travel"
choices.noApprovalAtWork = "Could not get approval at work"
choices.familyResponsibilities = "Family responsibilities"
choices.schedulingConflicts = "Scheduling conflicts"
choices.couldNotGetVisa = "Could not get a visa"
choices.healthIssues = "Health issues"

[questions.previousNixcons]
prompt = "Which previous NixCons did you attend in person?"
help = "Select all that apply."
choices.y2015Berlin = "2015: Berlin (Germany)"
choices.y2017Unterfohring = "2017: Unterföhring (Germany)"
choices.y2018London = "2018: London (UK)"
choices.y2019Brno = "2019: Brno (Czechia)"
choices.y2020Online = "2020: (online)"
choices.y2022Paris = "2022: Paris (France)"
choices.y2023Darmstadt = "2023: Darmstadt (Germany)"
choices.y2024Berlin = "2024: Berlin (Germany)"

[questions.moreSupport]
prompt = "In what way would you have appreciated more support?"
help = "If you attended remotely or not at all. Select all that apply."
choices.freeTicket = "Free ticket"
choices.helpAccommodation = "Help with finding accommodation"
choices.stipend = "Stipend (covered travel and accommodation costs)"

[questions.wentGreat]
prompt = "What do you think went great and should be done in future conferences too?"

[questions.notGreat]
prompt = "What do you think did not go great and should be avoided for future conferences?"

[questions.makeBetter]
prompt = "What else can we do to make future NixCons better?"

[questions.streams]
prompt = "Which streams did you tune in?"
choices.ownWebsite = "Our own website (2026.nixcon.org)"
choices.mediaCcc = "media.ccc.de (via streaming.media.ccc.de)"
choices.youtube = "YouTube (via youtube.com or any player app)"
choices.viewingParty = "Viewing party"

[questions.videoQuality]
prompt = "How was the video quality? (1-5)"
choices.v1 = "1"
choices.v2 = "2"
choices.v3 = "3"
choices.v4 = "4"
choices.v5 = "5"

[questions.videoImprove]
prompt = "How could the video quality be better?"

[questions.audioQuality]
prompt = "How was the audio quality? (1-5)"
choices.v1 = "1"
choices.v2 = "2"
choices.v3 = "3"
choices.v4 = "4"
choices.v5 = "5"

[questions.audioImprove]
prompt = "How could the audio quality be better?"

[questions.breakStreamTime]
prompt = "How can we fill the stream time during the breaks better?"

[questions.simultaneousTalks]
prompt = "What did you think of having multiple simultaneous talks/workshops in different rooms?"
choices.great = "Great, it allowed me to select what I cared about more"
choices.notGreat = "Not great, some of the content I wanted to see overlapped"
choices.noOpinion = "No opinion, I didn't go see many talks"

[questions.favouriteTalks]
prompt = "Which talks in the schedule did you like the most or stood out?"
help = "See https://talks.nixcon.org/nixcon-2026/schedule/"

[questions.dislikedTalks]
prompt = "Which talks did you not enjoy, and how could they be improved?"

[questions.breaksBetween]
prompt = "What did you think of the 10 minute breaks between talks?"
choices.tooShort = "Too short"
choices.justRight = "Just right"
choices.tooLong = "Too long"

[questions.startTimes]
prompt = "What did you think of the program starting times (10:00 Friday, 11:00 Saturday)?"
choices.tooEarly = "Started too early"
choices.justRight = "Just right"
choices.tooLate = "Started too late"

[questions.endTimes]
prompt = "What did you think of the program ending times (18:00 both Friday and Saturday)?"
choices.tooEarly = "Ended too early"
choices.justRight = "Just right"
choices.tooLate = "Ended too late"

[questions.talkLength]
prompt = "What did you think of the length of talks?"
choices.tooShort = "They were too short"
choices.justRight = "They were just right"
choices.tooLong = "They were too long"

[questions.talkNumber]
prompt = "What did you think of the number of talks?"
choices.tooFew = "There were too few"
choices.justEnough = "There were just enough"
choices.tooMany = "There were too many"

[questions.workshopNumber]
prompt = "What did you think of the number of workshops?"
help = "If you joined in-person."
choices.tooFew = "There were too few"
choices.justEnough = "There were just enough"
choices.tooMany = "There were too many"

[questions.skillLevel]
prompt = "What did you think of the skill level requirements?"
choices.tooAdvanced = "The talks were in general too advanced"
choices.justRight = "It was just right"
choices.tooBeginner = "The talks were in general too beginner-oriented"

[questions.outsideProgram]
prompt = "How did you enjoy your time at the venue outside the program (e.g. evenings, hallway track, side-quests)?"

[questions.negativeInteractions]
prompt = "Did you have any negative interactions with others you wish to tell us about?"

[questions.cameraPolicy]
prompt = "Did you have any issues with the camera policy (red lanyard for no picture)?"

[questions.communication]
prompt = "How satisfied were you with the communication and information availability during the event (e.g. opening ceremony, emails, matrix)?"

[questions.wristBands]
prompt = "Did you find the coloured wrist bands helpful in finding people with related interests?"
help = "Select all that apply."
choices.orange = "🧡 I wore an orange wrist band and got hugs"
choices.blue = "💙 I wore a blue wrist band and was approached for work offers"
choices.red = "❤️ I wore a red wrist band and received work offers"
choices.purple = "💜 I wore a purple wrist band and was approached by beginners"
choices.green = "💚 I wore a green wrist band and people approached me to discuss their Nixpkgs PRs"
choices.yellow = "💛 I wore a yellow wrist band and bee business happened 🐝"
choices.didNotUnderstand = "I did not understand the wrist bands"
choices.didNotWear = "I did not wear any wrist bands"
choices.woreButNoOne = "I wore wrist bands, but they didn't seem to attract anyone"
choices.thereWereBands = "There were wrist bands???"

[questions.sponsorships]
prompt = "How did you feel about the sponsorships and the presence of company representatives this year?"
choices.tooCorporate = "It was too corporate"
choices.goodTime = "I had a good time with the sponsors"
choices.moreCorporate = "There could be even more corporate presence"

[questions.venueThoughts]
prompt = "How did you find the venue (suitability, getting around, space, the view, ...)?"

[questions.ticketPrice]
prompt = "What did you think about the ticket price and the free tickets for contributors?"

[questions.payMoreForOthers]
prompt = "Would you be willing to pay more for your ticket, if the ticket sales helped more people attend NixCon?"
choices.yes = "Yes"
choices.no = "No"

[questions.moreSponsorsHelp]
prompt = "Would you be okay with seeing more sponsors at NixCon, if their sponsorship helped more people attend NixCon?"
choices.yes = "Yes"
choices.no = "No"

[questions.locationTradition]
prompt = "So far, NixCon has happened in a different location every year. Do you want this tradition to continue?"
choices.likeNewLocations = "I like seeing new locations, venues, and how different teams organise NixCons"
choices.preferSameVenue = "I would prefer less uncertainty in where and how NixCons are run, by having the same venue and team next year"

[questions.preferredDays]
prompt = "On what days do you prefer NixCon to take place?"
choices.satSun = "Sat-Sun (2 days)"
choices.friSun = "Fri-Sun (3 days)"
choices.satMon = "Sat-Mon (3 days)"
choices.friMon = "Fri-Mon (4 days)"

[questions.hackingTime]
prompt = "How would you prefer we schedule the dedicated hacking time (time in the schedule with no talks or workshops)?"
choices.noneNeeded = "No dedicated hacking time needed, I can hack in parallel to the talks"
choices.wholeDay = "I would like a whole day to be dedicated for hacking"
choices.someEachDay = "I would like to have some dedicated hacking time on each day"

[questions.anythingElse]
prompt = "Anything else you would like to add?"

[questions.bee]
prompt = "Bee?"
choices.yesHoney = "Yes, honey"
choices.bzz = "Bzz"
choices.noThanks = "No thanks"
