inputs:
let

  inherit (inputs.nixpkgs-lib)
    lib
    ;

  inherit (lib.attrsets)
    mapAttrs
    ;

  inherit (lib.trivial)
    const
    ;

in
mapAttrs (const (
  pkgs:
  (inputs.treefmt-nix.lib.evalModule pkgs {

    projectRootFile = "flake.nix";

    settings.global.excludes = [
      # Raw survey responses (never committed) and LimeSurvey exports.
      "*.csv"
      "*.lss"
      # Generated by the pipeline; must stay byte-identical to its producer.
      "overlays/top-level/nixos-surveys-community-2025-data/results-2025.json"
      # The Astro site has no formatter yet; prettier needs an Astro plugin.
      "lib/site/*"
      "flake.lock"
    ];

    programs.deadnix.enable = true;
    programs.deadnix.no-lambda-pattern-names = true;

    # commentary.md is content the pipeline embeds in the results JSON;
    # reformatting it would change the vendored data.
    programs.mdformat.enable = true;
    programs.mdformat.excludes = [ "community/*/commentary.md" ];

    programs.nixfmt.enable = true;

    programs.ruff-check.enable = true;
    programs.ruff-format.enable = true;

    programs.statix.enable = true;

    programs.taplo.enable = true;

  })
)) inputs.self.legacyPackages
